### ISSUE TITLE
Process for adding content

### ISSUE THREAD

**Issue by sirkitree** [j-hannah/js-report#10]
## Motivation
We want to make it as easy as possible for people to help gather content. For that we have to outline how they can contribute with clear instructions and make it as easy as possible for that contribution to happen.

## Questions to answer
What is this process currently?

Is there a way we can make this super easy, like adding a link somewhere ends up automatically filling out the required fields for us in CosmicJS?

## Tasks
* [ ] document our process
* [ ] look into automating the addition of content as much as possible
* [ ] update documentation after we automate this further

**Comment by j-hannah** [comment]
@sirkitree This looks great! Where would be the best place to document the current process - just put it in the README? Regarding grabbing content from a url, that sounds really interesting. Possibly kinda hard too. 

One thing that pops into mind is creating a separate app were we could do that and then populate form fields for possible editing before submission. You'll see the PR I have, but I'd like to move over to Contentful. I don't know if that impacts what we do with auto-adding or not. This sort of thing could be a really great project.

**Comment by j-hannah** [comment]
@sirkitree what do you think is the best approach to adding the curated articles? Currently I just add the content from the original post. The part I'm wondering about in particular is the blurb. I'm just using the first paragraph or two. Is this adequate? Should the standard be that the contributor adds a brief summary? I haven't been doing that because I worried that approach would meet the same fate as the Front End Rapport. On the other add, is may add value/insight for the contributor to write an intro paragraph. Not sure. What do you think?

**Comment by sirkitree** [comment]
I think that we should be using the meta data if we can. Think about typical sharing functionality and opengraph tags: when you share something to twitter/fb/etc, they pull data from the meta first (image + blurb) and if that doesn't exist we could then make sure it is edited.

I don't know how this will work with Contentful, if they have the capability already to pull that data from a url, or if we can even extend a url field in Contentful to do something like that. 

It may need to be part of this app, like a way to log in, put in a url, grab the opengraph data, then post it into Contentful, which then displays on the front page. This would give us the ability to curate right from this app. 

Could be a good opportunity to use an SSO for login (take your pick btwn G+/FB/Twitter/GitHub) and even create a react module around that if one doesn't already exist. 

I could see the grabbing of opengraph meta data being a module as well (might already exist too) which then puts data into a text field for us to have the opportunity to edit before we submit to Contentful.
